package entities;

import entities.maturity_and_categoryPlant.CategoriePlanta;
import entities.maturity_and_categoryPlant.Maturity;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a Plant entity in the simulation.
 * Manages growth, oxygen generation, and blocking probability based on maturity.
 */
@Getter @Setter
public class Plant extends Entities {

    private static final double GROWTH_INCREMENT = 0.2;
    private static final double ROUNDING_FACTOR = 100.0;
    private static final int MATURE_THRESHOLD = 1;
    private static final int OLD_THRESHOLD = 2;
    private static final int DEAD_THRESHOLD = 3;

    private CategoriePlanta categoriePlanta;
    private Maturity maturity = Maturity.Young;
    private double index = 0;
    private int initialTime = 0;

    /**
     * Constructs a new Plant instance.
     *
     * @param type The type of the plant (used to determine category).
     * @param name The name of the plant.
     * @param mass The initial mass of the plant.
     */
    public Plant(final String type, final String name, final double mass) {
        super(type, name, mass);
        this.categoriePlanta = CategoriePlanta.getCategoryByType(type);
    }

    /**
     * Calculates the amount of oxygen generated by the plant.
     * Based on the plant category and its current maturity level.
     *
     * @return The amount of oxygen generated.
     */
    public double genO2() {
        double o2plant = categoriePlanta.getOxigen();
        double o2mat = maturity.getMaturity();
        return o2plant + o2mat;
    }

    /**
     * Increments the plant's growth index and updates its maturity status.
     * The index is incremented by a fixed growth factor.
     * Maturity transitions occur at specific index thresholds.
     */
    public void addIndex() {
        index += GROWTH_INCREMENT;
        index = Math.round(index * ROUNDING_FACTOR) / ROUNDING_FACTOR;

        if (index >= MATURE_THRESHOLD && index < OLD_THRESHOLD) {
            maturity = Maturity.Mature;
        }
        if (index >= OLD_THRESHOLD && index < DEAD_THRESHOLD) {
            maturity = Maturity.Old;
        }
        if (index >= DEAD_THRESHOLD) {
            maturity = Maturity.Dead;
        }
    }

    /**
     * Retrieves the probability of this plant blocking movement or light.
     *
     * @return The blocking probability based on the plant's category.
     */
    public double blockProbability() {
        return categoriePlanta.getProbability();
    }
}
